### ISSUE TITLE
Email address changes

### ISSUE THREAD

**Issue by LaurenRhodes** [nasa-gcn/gcn.nasa.gov#2643] opened 2024-10-24 20:17 UTC
Hey GCN people :) 

I was wondering would be possible to add the option of changing the email address associated with a given account? Given how often people in academia move jobs, and therefore email addresses, it would be really amazing if gcn accounts had the ability to change email addresses so that we don't have to delete the old one and create a new one each time we move job. 

Cheers

Lauren

**Comment by lpsinger** [comment] 2024-10-25 14:29
This is a very common request, and a long term goal of ours. Unfortunately, our identity and access management product ([Amazon Cognito](https://aws.amazon.com/cognito/)) does not support it.

**Comment by lpsinger** [comment] 2024-10-25 14:30
Duplicate of #411.

**Closed by lpsinger** 2024-10-25 14:30 UTC
