### ISSUE TITLE
GCN documentation for corrections is a blank page with the header "Corrections"

### ISSUE THREAD

**Issue by jak574** [nasa-gcn/gcn.nasa.gov#2202] opened 2024-04-15 23:03 UTC
# Current behavior

Visiting this page: https://gcn.nasa.gov/docs/circulars/corrections results in a blank page with "Corrections".

<img width="524" alt="Screenshot 2024-04-15 at 18 59 35" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/15330708/c0eaa620-9c0c-407a-b650-bda6a70e9758">

The corrections policy is well documented in the Code of Conduct.

# Expected behavior

Corrections page actually show information about Corrections. Either that or remove this section and direct people to the code of conduct which has a section on Errata which I believe covers what should be on this page, at least the policy part.

# Steps to reproduce

Go here: https://gcn.nasa.gov/docs/circulars/corrections

This page was reached by clicking "Documentation", then "Circulars" and "Corrections".

# Environment

Mac OS 14. Safari 17.4.1.

**Comment by lpsinger** [comment] 2024-04-15 23:10
Duplicate of #2154.

**Closed by lpsinger** 2024-04-15 23:10 UTC
Labels: bug
