### ISSUE TITLE
mechanism for announcing changes to schema before new version takes effect

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#1618] opened 2023-11-02 16:33 UTC
Question from Sam Wyatt at LVEM Open meeting Nov 2, 2023.

**Comment by lpsinger** [comment] 2023-11-02 16:36
CC @swyatt7.

**Comment by lpsinger** [comment] 2024-01-23 16:03
Duplicate of #773.

**Closed by lpsinger** 2024-01-23 16:03 UTC
