### ISSUE TITLE
GCN Circulars: Remove submitted by

### ISSUE THREAD

**Issue by Vidushi-GitHub** [nasa-gcn/gcn.nasa.gov#1240] opened 2023-08-16 20:07 UTC
Just a quick fix, we had a discussion over removing the submitted by (legacy/web-form etc.) in the circulars, as we have inclusive policy.
But it would be nice to keep the information as a hidden file.

**Comment by lpsinger** [comment] 2023-08-17 01:28
Duplicate of #1202.

**Closed by lpsinger** 2023-08-17 01:28 UTC
