### ISSUE TITLE
different circulars display depending on query

### ISSUE THREAD

**Issue by nuessle167** [nasa-gcn/gcn.nasa.gov#1293] opened 2023-08-25 20:45 UTC
If query is entered as "YYMMDDA", then most relevant circulars are displayed, including future bursts referencing the queried burst. This should probably be noted as the preferred retrieval method.
If query is entered as "YYMMDD", then no circulars are returned even when events are known to have occured. This should probably return data about the events associated with date, much as queries about "supernova" or "kilonova" return circulars that are associated with those events.
If query is entered as "GRBYYMMDDA", then few if any circulars are displayed, and usually only future bursts which reference the queried burst. This should probably return the same as the burst name alone, rather than a very limited subset.
If query is entered as "GRBYYMMDD", then no circulars are returned. This should probably return the same as the burst number alone, rather than nothing.
If query is entered as "GRB YYMMDDA", then all GRB-adjacent notices ever entered into the GCN are displayed. This should probably be noted as the wrong way to enter GRB names, as it's really a database parsing issue.

**Comment by jracusin** [comment] 2023-08-25 22:19
Pi, the search isn't parsing the date and using that to search, it's just searching for those strings. So when you just include YYMMDDL, it's finding any use of that. When you search GRBYYMMDDL, it's finding circulars where authors didn't include a space, and when you search "GRB YYMMDDL", it's searching for both "GRB" and "YYMMDDL". So it's working as intended, even if not intuitive.

We are working on searching by date, but that's still in progress. See #878.

**Comment by nuessle167** [comment] 2023-08-25 23:20
Okay, I’ll close the issue. Thank you!

Pi Nuessle
They/them/theirs (español: elle, Nederlands: ze/hun)
Physics Ph.D. Candidate George Washington University
Higher Education Teaching M.Sc., Purdue University Global 2022
High-Performance Computing Masters Certificate, GWU 2021
B.Sc. Physics-Mathematics, Rose-Hulman 2018
________________________________

**Comment by lpsinger** [comment] 2023-08-26 01:01
Is this, then, a duplicate of #878?

**Comment by nuessle167** [comment] 2023-08-28 16:51
this is a duplicate of #878

**Closed** 2023-08-28 16:50 UTC
