### ISSUE TITLE
Non-working links on page detailing Swift GUANO Kafka alerts

### ISSUE THREAD

**Issue by jak574** [nasa-gcn/gcn.nasa.gov#1670] opened 2023-11-17 18:18 UTC
The following page:

https://gcn.nasa.gov/missions/swift#json-serialized-gcn-notice-types-in-gcn-kafka

contains several links that do not function:
* [GCN Schema](https://gcn.nasa.gov/schema/stable/gcn/notices/swift/bat/guano.schema.json) leads to a "404: Not Found".
* [JSON Message](https://raw.githubusercontent.com/nasa-gcn/gcn-schema/v3.0.0/gcn/notices/swift/bat/guano.example.json) leads to a "404: Not Found"
* [Schema Browser](https://gcn.nasa.gov/docs/schema/v3.0.0/gcn/notices/swift/bat/guano.example.json) leads to a GCN page with the error "Unexpected error. An unexpected error occurred."
* [Detailed Description and Examples](https://github.com/nasa-gcn/gcn-schema/tree/main/gcn/notices/swift/bat/guano) leads to a "404 - page not found"

**Comment by lpsinger** [comment] 2023-11-17 18:39
Good catch! It looks like in many cases the problem is a matter of capitalization: https://github.com/nasa-gcn/gcn-schema/tree/main/gcn/notices/swift/bat

@jak574, would you be interested in attempting a PR for this, to get some practice with editing Markdown content in Remix? If not, then I can write a PR later this afternoon.

**Comment by jak574** [comment] 2023-11-17 20:02
@lpsinger I'll give it a go.

**Comment by jak574** [comment] 2023-11-17 20:55
I submitted https://github.com/nasa-gcn/gcn.nasa.gov/pull/1673

**Comment by lpsinger** [comment] 2023-11-18 13:24
Fixed by #1673.

**Closed by lpsinger** 2023-11-18 13:24 UTC
